config/routes.rb
Rails.application.routes.draw do
  resources :pages  
  resources :representatives
  resources :legislatures
  
  resources :legislatures_representatives

  namespace :admin do
    resources :dashboard
    resources :observers do 
      put 'activate' => 'observers#activate', on: :member
      put 'deactivate' => 'observers#deactivate', on: :member
    end 
    resources :legislatures
    resources :commission_topics
    resources :commissions
    root 'dashboard#index'
  end

  devise_for :users

  root 'pages#index'
end

app/models/commission.rb
class Commission < ActiveRecord::Base
  belongs_to :commission_topic
  belongs_to :legislature

  has_many :commission_representatives

  validates :legislature_id, :name, :commission_topic_id, presence: true
end

app/models/commission_representative.rb
class CommissionRepresentative < ActiveRecord::Base
  belongs_to :commission
  belongs_to :representative
end

app/models/commission_topic.rb
class CommissionTopic < ActiveRecord::Base
  has_many :commissions
end

app/models/district.rb
class District < ActiveRecord::Base
  has_many :legislature_representatives
end

app/models/education.rb
class Education < ResumeEntry
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  has_many :votes
end

app/models/legislature.rb
class Legislature < ActiveRecord::Base
  enum status: [:inactive, :active]

  has_many :legislature_representatives

  validates :name, presence: true
end

app/models/legislature_representative.rb
class LegislatureRepresentative < ActiveRecord::Base
  belongs_to :district
  belongs_to :party
  belongs_to :seat

  belongs_to :representative
  belongs_to :legislature

  enum status: [:inactive, :active]
end

app/models/party.rb
class Party < ActiveRecord::Base
  enum status: [:inactive, :active]
end

app/models/representative.rb
class Representative < ActiveRecord::Base
  #voted= Votado, pluri = plurinominal
  enum representative_type: [ :voted, :pluri ]

  has_many :commission_representatives
  has_many :legislature_representatives
  has_many :votes
end

app/models/resume_entry.rb
class ResumeEntry < ActiveRecord::Base
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  has_many :legislature_representatives
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable,
         :rememberable, :trackable, :validatable

  enum role: [ :observer, :root ]
  enum status: [:active, :inactive]

  scope :observers, -> { where(role: "observer") }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :initiative
  belongs_to :representative
end

app/models/work_information.rb
class WorkInformation < ResumeEntry
end

app/controllers/admin/commission_topics_controller.rb
class Admin::CommissionTopicsController < Admin::BaseController	
	before_action :authenticate_user!, only: [:create]
	before_action :set_commission_topic, only: [:show]

	def index
		@commission_topics = CommissionTopic.all
	end

	def new
		@commission_topic = CommissionTopic.new
	end

	def show
	end

	def create
		@commission_topic = CommissionTopic.new(commission_topics_params)

    respond_to do |format|
      if @commission_topic.save
        format.html { redirect_to admin_commission_topic_path(@commission_topic) }
      else
        format.html { render :new }
      end
    end  
	end

	private

	def set_commission_topic
		@commission_topic = CommissionTopic.find(params[:id])
	end

	def commission_topics_params
		params.require(:commission_topic).permit(:name, :description)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/legislatures_controller.rb
class LegislaturesController < ApplicationController

  before_action :set_legislature, only: [:edit, :update, :show]

  def index
    @legislatures = Legislature.all
  end

  def new
    @legislature = Legislature.new
  end

  def show
    @legilature = Legislature.find(params[:id])
  end

  def create
    @legislature = Legislature.new(legislature_params)

    respond_to do |format|
      if @legislature.save
        format.html { redirect_to @legislature }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @legislature.update(legislature_params)
        format.html { redirect_to @legislature, notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_legislature
    @legislature = Legislature.find(params[:id])
  end

  def legislature_params
    params.require(:legislature).permit(:name, :status, :starts_on, :ends_on)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController

	before_action :authenticate_user!, only: [:create] 

	def index
		@representatives = Representative.all
	end

	def create
		@representative = Representative.new(representative_params)
		if @representative.save
			@representative
		end
	end

	private
		
	def representative_params
		params.require(:representative).permit(:first_name,:last_name, :email, :phone, :represetative_type, :twitter,:facebook)
	end
	
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/commission_topics/_form.html.erb
<%= form_for @commission_topic, url: admin_commission_topics_path(@commission_topic) do |f| %>
  <% if @commission_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commission_topic.errors.count, "error") %> prohibited this commission topic from being saved:</h2>

      <ul>
      <% @commission_topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/commission_topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Commission Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commission_topics.each do |commission_topic| %>
      <tr>
        <td><%= commission_topic.name %></td>
        <td><%= commission_topic.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Commission Topic', new_admin_commission_topic_path %>

app/views/admin/commission_topics/new.html.erb
<h1>New Commission Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_commission_topics_path %>

app/views/admin/commission_topics/show.html.erb
<%= @commission_topic.name %>