config/routes.rb
Rails.application.routes.draw do
  resources :pages  
  resources :representatives
  resources :legislatures
  
  resources :legislatures_representatives

  namespace :admin do
    resources :dashboard
    resources :observers do 
      put 'activate' => 'observers#activate', on: :member
      put 'deactivate' => 'observers#deactivate', on: :member
    end 
    resources :legislatures
    resources :commission_topics
    resources :commissions
    root 'dashboard#index'
  end

  devise_for :users

  root 'pages#index'
end

app/models/commission.rb
class Commission < ActiveRecord::Base
  belongs_to :commission_topic
  belongs_to :legislature

  has_many :commission_representatives

  validates :legislature_id, :name, :commission_topic_id, presence: true
end

app/models/commission_representative.rb
class CommissionRepresentative < ActiveRecord::Base
  belongs_to :commission
  belongs_to :representative
end

app/models/commission_topic.rb
class CommissionTopic < ActiveRecord::Base
  has_many :commissions
end

app/models/district.rb
class District < ActiveRecord::Base
  has_many :legislature_representatives
end

app/models/education.rb
class Education < ResumeEntry
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  has_many :votes
end

app/models/legislature.rb
class Legislature < ActiveRecord::Base
  enum status: [:inactive, :active]

  has_many :legislature_representatives

  validates :name, presence: true
end

app/models/legislature_representative.rb
class LegislatureRepresentative < ActiveRecord::Base
  belongs_to :district
  belongs_to :party
  belongs_to :seat

  belongs_to :representative
  belongs_to :legislature

  enum status: [:inactive, :active]
end

app/models/party.rb
class Party < ActiveRecord::Base
  enum status: [:inactive, :active]
end

app/models/representative.rb
class Representative < ActiveRecord::Base
  #voted= Votado, pluri = plurinominal
  enum representative_type: [ :voted, :pluri ]

  has_many :commission_representatives
  has_many :legislature_representatives
  has_many :votes
end

app/models/resume_entry.rb
class ResumeEntry < ActiveRecord::Base
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  has_many :legislature_representatives
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable,
         :rememberable, :trackable, :validatable

  enum role: [ :observer, :root ]
  enum status: [:active, :inactive]

  scope :observers, -> { where(role: "observer") }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :initiative
  belongs_to :representative
end

app/models/work_information.rb
class WorkInformation < ResumeEntry
end

app/controllers/admin/legislatures_controller.rb
class Admin::LegislaturesController < Admin::BaseController
  before_action :authenticate_user!, only: [:create, :update]
  before_action :set_legislature, only: [:edit, :update, :show]

  def index
    @legislatures = Legislature.all
  end

  def new
    @legislature = Legislature.new
  end

  def show
    
  end

  def create
    @legislature = Legislature.new(legislature_params)

    respond_to do |format|
      if @legislature.save
        format.html { redirect_to admin_legislatures_path(@legislature) }
      else
        format.html { render :new }
      end
    end    
  end

  def edit
  end

  def update
    respond_to do |format|
      if @legislature.update(legislature_params)
        format.html { redirect_to admin_legislatures_path(@legislature), notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end    
  end

  private

  def set_legislature
    @legislature = Legislature.find(params[:id])
  end

  def legislature_params
    params.require(:legislature).permit(:name, :status, :starts_on, :ends_on)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/legislatures_controller.rb
class LegislaturesController < ApplicationController

  before_action :set_legislature, only: [:edit, :update, :show]

  def index
    @legislatures = Legislature.all
  end

  def new
    @legislature = Legislature.new
  end

  def show
    @legilature = Legislature.find(params[:id])
  end

  def create
    @legislature = Legislature.new(legislature_params)

    respond_to do |format|
      if @legislature.save
        format.html { redirect_to @legislature }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @legislature.update(legislature_params)
        format.html { redirect_to @legislature, notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_legislature
    @legislature = Legislature.find(params[:id])
  end

  def legislature_params
    params.require(:legislature).permit(:name, :status, :starts_on, :ends_on)
  end
end

app/controllers/legislatures_representatives_controller.rb
class LegislaturesRepresentativesController < ApplicationController
	before_action :authenticate_user!, only: [:create] 

	def new
		@legislatures = Legislature.where(status: 1 )
		@representatives = Representative.all
		@seats = Seat.all
		@partys = Party.all
		@districts = District.all
	end

	def create
		@legislature_representative = LegislatureRepresentative.new(legislature_representative_params)
		if @legislature_representative.save
			@legislature_representative
		end
	end

	private
	def legislature_representative_params
		params.require(:legislature_representative).permit(:legislature_id, :representative_id, :seat_id, :party_id, :district_id)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController

	before_action :authenticate_user!, only: [:create] 

	def index
		@representatives = Representative.all
	end

	def create
		@representative = Representative.new(representative_params)
		if @representative.save
			@representative
		end
	end

	private
		
	def representative_params
		params.require(:representative).permit(:first_name,:last_name, :email, :phone, :represetative_type, :twitter,:facebook)
	end
	
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/legislatures/_form.html.erb
<%= form_for [:admin, @legislature], html: { class: 'form-horizontal'} do |f| %>
  <% if @legislature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@legislature.errors.count, "error") %> prohibited this legislature from being saved:</h2>
      <ul>
      <% @legislature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :starts_on, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :starts_on, type: 'date', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :ends_on, class: 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_field :ends_on, type: 'date', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <label><%= f.check_box :status %> Activo</label>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <button type='submit' class='btn btn-primary'>Save</button>
    </div>
  </div>
<% end %>

app/views/admin/legislatures/edit.html.erb
<h1>Editing Legislature</h1>

<%= render 'form' %>

<%= link_to 'Show', @legislature %> |
<%= link_to 'Back', admin_legislatures_path %>

app/views/admin/legislatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Legislatures</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Starts On</th>
      <th>Ends On</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @legislatures.each do |legislature| %>
      <tr>
        <td><%= legislature.name %></td>
        <td><%= legislature.status %></td>
        <td><%= legislature.starts_on %></td>
        <td><%= legislature.ends_on %></td>
        <td><%= link_to 'Edit', edit_admin_legislature_path(legislature) %></td>td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New legislature', new_admin_legislature_path %>

app/views/admin/legislatures/new.html.erb
<h1>New Legislature</h1>

<%= render 'form' %>

<%= link_to 'Back', legislatures_path %>

app/views/admin/legislatures/show.html.erb
<%= @legislature.name %>