config/routes.rb
Rails.application.routes.draw do
  resources :pages  
  resources :representatives
  resources :legislatures
  
  resources :legislatures_representatives

  namespace :admin do
    resources :dashboard
    resources :observers do 
      put 'activate' => 'observers#activate', on: :member
      put 'deactivate' => 'observers#deactivate', on: :member
    end 
    resources :legislatures
    resources :commission_topics
    resources :commissions
    root 'dashboard#index'
  end

  devise_for :users

  root 'pages#index'
end

app/models/commission.rb
class Commission < ActiveRecord::Base
  belongs_to :commission_topic
  belongs_to :legislature

  has_many :commission_representatives

  validates :legislature_id, :name, :commission_topic_id, presence: true
end

app/models/commission_representative.rb
class CommissionRepresentative < ActiveRecord::Base
  belongs_to :commission
  belongs_to :representative
end

app/models/commission_topic.rb
class CommissionTopic < ActiveRecord::Base
  has_many :commissions
end

app/models/district.rb
class District < ActiveRecord::Base
  has_many :legislature_representatives
end

app/models/education.rb
class Education < ResumeEntry
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  has_many :votes
end

app/models/legislature.rb
class Legislature < ActiveRecord::Base
  enum status: [:inactive, :active]

  has_many :legislature_representatives

  validates :name, presence: true
end

app/models/legislature_representative.rb
class LegislatureRepresentative < ActiveRecord::Base
  belongs_to :district
  belongs_to :party
  belongs_to :seat

  belongs_to :representative
  belongs_to :legislature

  enum status: [:inactive, :active]
end

app/models/party.rb
class Party < ActiveRecord::Base
  enum status: [:inactive, :active]
end

app/models/representative.rb
class Representative < ActiveRecord::Base
  #voted= Votado, pluri = plurinominal
  enum representative_type: [ :voted, :pluri ]

  has_many :commission_representatives
  has_many :legislature_representatives
  has_many :votes
end

app/models/resume_entry.rb
class ResumeEntry < ActiveRecord::Base
end

app/models/seat.rb
class Seat < ActiveRecord::Base
  has_many :legislature_representatives
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:recoverable,
         :rememberable, :trackable, :validatable

  enum role: [ :observer, :root ]
  enum status: [:active, :inactive]

  scope :observers, -> { where(role: "observer") }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :initiative
  belongs_to :representative
end

app/models/work_information.rb
class WorkInformation < ResumeEntry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/legislatures_controller.rb
class LegislaturesController < ApplicationController

  before_action :set_legislature, only: [:edit, :update, :show]

  def index
    @legislatures = Legislature.all
  end

  def new
    @legislature = Legislature.new
  end

  def show
    @legilature = Legislature.find(params[:id])
  end

  def create
    @legislature = Legislature.new(legislature_params)

    respond_to do |format|
      if @legislature.save
        format.html { redirect_to @legislature }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @legislature.update(legislature_params)
        format.html { redirect_to @legislature, notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def set_legislature
    @legislature = Legislature.find(params[:id])
  end

  def legislature_params
    params.require(:legislature).permit(:name, :status, :starts_on, :ends_on)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
 <footer>
    <hr>
    <p>&copy; Congreso Abierto 2016</p>
  </footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Congreso Abierto", root_path, class: "navbar-brand" %>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav navbar-left">

          <li> <a href="#">Diputados</a> </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? -%>
              <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <% if current_user.root? %>
                        <li><%= link_to 'Dashboard', admin_root_path %></li>
                      <% end %>
                      <li><%= link_to 'Profile', "#" %></li>
                      <li role="separator" class="divider"></li>
                      <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>

                    </ul>
               </li>
            <% else -%>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end -%>
          </ul>
      </div>
    </div>
  </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Congreso Abierto" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container-fluid">
      <div class="row">
        <div class="col-md-3">

          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to 'Home', admin_root_path %></li>
            <li><%= link_to 'Observers', admin_observers_path %></li>
            <li><%= link_to 'Legislatures', admin_legislatures_path %></li>
          </ul>


        </div>
        <div class="col-md-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

     <%= render 'layouts/footer' %>


    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Congreso Abierto" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
       
      </div><!--/row-->

     <%= render 'layouts/footer' %>


    </div> <!-- /container -->

  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name %> from being saved:</h3>
    </div>
    <div class="panel-body">
      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>